ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

CURRENT_DIR := $(shell dirname $(shell pwd))

USER_LIB_PATH += $(CURRENT_DIR)/include/arena_control
ARDUINO_LIBS += ros_lib

BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk