ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH += /home/$(USER)/LaboratoryRepository/Arduino/libraries
ARDUINO_LIBS += ros_lib

BOARD_TAG = uno

include /usr/share/arduino/Arduino.mk

